import type { DiyPageData } from '@/pages/diy/page/types'

export function createDiyPageData(): DiyPageData {
  return {
    statusBarHeight: 24,
    navigationHeight: 48,
    diyPageTitle: '晶石实验室',
    entryMaskVisible: true,
    entryMaskLeaving: false,
    entryStatusText: '正在准备 DIY 设计台…',
    entryStatusDetail: '正在加载材料与编辑器',
    entryErrorText: '',
    canvasReady: false,
    loadingMaterials: true,
    materialsError: '',
    mainCategories: [],
    currentCategory: '',
    subcategories: [],
    currentSubcategory: 'all',
    searchQuery: '',
    materialGroups: [],
    hasMoreMaterials: false,
    beadCount: 0,
    totalPriceText: '0',
    perimeterText: '0.0 mm',
    wristMessage: '待生成',
    wristFitWarningVisible: false,
    wristFitWarningText: '',
    canUndo: false,
    canSave: false,
    showSaveNameDialog: false,
    designNameDraft: '',
    savingDesign: false,
    showGuide: false,
    showWristPicker: false,
    selectedWristCm: null,
    selectedWristStrands: 1,
  }
}
